# Generated by Django 5.1.6 on 2025-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    (1, "Pending"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (-2, "Refunded"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
