# Generated by Django 5.1.6 on 2025-05-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="all_amount",
            new_name="total_amount",
        ),
    ]
