# Generated by Django 5.1.6 on 2025-05-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_all_amount_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (-2, "Refunded"),
                ],
                default=1,
            ),
        ),
    ]
