# Generated by Django 5.1.6 on 2025-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_cancel_time_payment_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
