# Generated by Django 5.1.6 on 2025-04-01 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/users/"),
        ),
        migrations.CreateModel(
            name="OnboardingAnswers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("endurance", "Improve Endurance"),
                            ("strength", "Increase Strength"),
                            ("maintenance", "Maintain Fitness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("one_month", "One Month"),
                            ("two_three_months", "Two Three Months"),
                            ("long_term", "Long Term"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "training_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("twice", "Twice"),
                            ("three_to_four", "Three to four"),
                            ("five_plus", "Five Plus"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "consultation",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
