# Generated by Django 5.1.6 on 2025-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
