# Generated by Django 5.1.6 on 2025-04-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_service_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
