# Generated by Django 5.1.6 on 2025-04-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_video_service_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
    ]
